# Generated by Django 4.1.1 on 2022-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=100)),
                ("benefit1", models.CharField(max_length=100)),
                ("benefit2", models.CharField(max_length=100)),
                ("benefit3", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Saving",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saving_name", models.CharField(max_length=100)),
                ("period", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("interest_rate", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="consume", old_name="beauty", new_name="education",
        ),
    ]
