# Generated by Django 4.1.2 on 2022-10-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="available_asset",
            field=models.CharField(max_length=100),
        ),
    ]
