# Generated by Django 4.1.1 on 2022-10-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webuser",
            options={
                "managed": False,
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
