# Generated by Django 4.1.1 on 2022-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_alter_webuser_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAct",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("act", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={"db_table": "stock_act", "managed": False,},
        ),
        migrations.CreateModel(
            name="StockChart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("open", models.IntegerField()),
                ("close", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
            ],
            options={"db_table": "stock_chart", "managed": False,},
        ),
        migrations.CreateModel(
            name="StockInteg",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("close", models.BigIntegerField(blank=True, null=True)),
                ("diff", models.IntegerField(blank=True, null=True)),
                ("diff_ratio", models.FloatField(blank=True, null=True)),
                ("open", models.BigIntegerField(blank=True, null=True)),
                ("high", models.BigIntegerField(blank=True, null=True)),
                ("low", models.BigIntegerField(blank=True, null=True)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={"db_table": "stock_integ", "managed": False,},
        ),
        migrations.DeleteModel(name="ApartInfo",),
    ]
