# Generated by Django 4.1.1 on 2022-10-11 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_card_saving_rename_beauty_consume_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="age",
            field=models.ForeignKey(
                db_column="age",
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saving",
            name="age",
            field=models.ForeignKey(
                db_column="age",
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
